# Generated by Django 3.0.3 on 2020-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.TextField()),
                ('photo', models.TextField(null=True)),
                ('favorite', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
